# Obsidianのvaultパス
vault_path: "C:\\Users\\username\\Documents\\Obsidian\\MyVault"

# 要約対象のタグ
target_tag: "要約"

# メール設定
email:
  enabled: true  # メール送信の有効/無効を制御（false: メール送信をスキップし、ログにのみ出力）
  from: "your-email@example.com"
  # 配列形式で複数の送信先を指定する場合
  to:
    - "recipient1@example.com"
    - "recipient2@example.com"
    - "recipient3@example.com"
  # または、カンマ区切りの文字列で指定することも可能
  # to: "recipient1@example.com, recipient2@example.com, recipient3@example.com"
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  password: "your-app-specific-password"

# OpenAI API設定
openai:
  api_key: "sk-your-api-key-here"
  model: "gpt-4"
  max_tokens: 800
  additional_prompt: |
    以下の指示に従って要約を作成してください：
    1. 各ノートの重要なポイントを3点にまとめる
    2. 技術的な用語は可能な限り平易な言葉で説明する
    3. アクションアイテムがある場合は、末尾に箇条書きでまとめる

# 検索対象期間の設定
search_period:
  # 検索対象とする日数（1なら当日のみ、2なら前日も含む、など）
  days: 1
  # 検索開始時刻（オプション、指定がない場合は当日0時から）
  start_time: "00:00"
  # 検索終了時刻（オプション、指定がない場合は現在時刻まで）
  end_time: "23:59"

# ログ設定
logging:
  retention_days: 7
  directory: "logs"
